### PR TITLE
Supporting GTK4

### PR DESCRIPTION
**Pull request by Ghostkeeper**
Maybe you don't want to merge this. Read carefully.

I updated to Ubuntu 21.10, which is based on GTK4. I found that this Gnome extension didn't work because of that, and that nobody was around to fix that. So I gave it a try, and it's working.

There is one major bug with this currently as far as I could find: When changing the provider, the provider page doesn't update. You'd need to disable and re-enable the extension to make it update. I don't really have any experience with GTK but I'm decent at fiddling. I could probably fix that issue at some point if I get around to it, but I really don't have much of an idea of what I'm doing. The only front-end framework I've really used is Qt. So I'm also publishing this PR as a draft in the hope that someone comes around to see what I did wrong.

I didn't test it, but this change probably means that older versions of GTK are not supported any more. And that's a problem with many people still on GTK3 (especially since Ubuntu LTS still is). This could be a reason not to merge this and perhaps split the code bases permanently.

I know you don't want to maintain this extension any more though, so there's a couple of things we can do (after that bug is fixed):
* You could just merge it, upload a new version on extensions.gnome.org. However that means that people on GTK3 won't be able to use it.
* You could try and make it work for both GTK3 and GTK4. It's probably possible. I'm not up for that task though.
* I'm also willing to take over the project permanently as a maintainer. I maintain several other small projects like this. However when I do that, I'd Keep It Simple, Stupid and probably delete/hide the whole mechanism of extensible providers as soon as the first bug with that is discovered, just have it put up random files from a folder. That's what I'm using it for anyway. I would publish that as "v3" of the extension, just like you did as "v2".

I'm not in it for the fame or anything. Just want to help.

### CODE REVIEW

**Comment by ssk101** [comment]
I have no plans to go back to Gnome again, so you're more than welcome to take the project over.

**Comment by ssk101** [comment]
https://github.com/ssk101/gnome-wallpaper-changer-v2/pull/6

@Ghostkeeper If you rename/delete your fork I can transfer the repo to you.

**Comment by Ghostkeeper** [comment]
Okay, will rename it then.

**Comment by ssk101** [comment]
> Okay, will rename it then.

Looks like you'll have to delete the fork for a transfer to work, actually.

**Comment by Ghostkeeper** [comment]
Right. It's deleted now.

I still have the commits in a local clone (and I'm actively using it right now), in case your PR doesn't survive the transfer.

**Comment by Ghostkeeper** [comment]
I'm sorry, the transfer apparently expired. Could you try again?

**Comment by ssk101** [comment]
> I'm sorry, the transfer apparently expired. Could you try again?

Done

**Pull request closed without merging**
